apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: liveaaz-backend
  labels:
    app: liveaaz-backend
data:
  RELEVANTZ_LDAP_LOGIN_IP: "192.168.8.1"
  RELEVANTZ_LDAP_LOGIN_USERNAME: "dgouser"
  RELEVANTZ_LDAP_LOGIN_FQDN: "DC.rgo.local"
  RELEVANTZ_LDAP_LOGIN_ACSUFFIX: "@rgo.local"
  RELEVANTZ_LDAP_LOGIN_RDN: "@RGO"
  RELEVANTZ_LDAP_LOGIN_BASEDN: "CN=Users,DC=rgo,DC=local"
  RELEVANTZ_LDAP_LOGIN_PORT: "636"
  FRONTEND_URL: "http://127.0.0.1:59498"
  PORT: "5005"
  MONGODB_URI: "mongodb://host.docker.internal:27017/livEAAZ360_db"
  LDAP_URL: "ldap://localhost:389"
  LDAP_BASE_DN: "ou=users,dc=example,dc=com"
